server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: npminhtri.be@gmail.com  # Thông tin email
    password: cfubhnaxnbdzsnta  # Thông tin mật khẩu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=EducationSystem;encrypt=true;trustServerCertificate=true
    username: sa  # Tên người dùng CSDL
    password: 12345678  # Mật khẩu CSDL
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyNoOpImpl  # Giữ nguyên tên bảng và cột không thay đổi
          implicit-naming-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl  # Giữ nguyên tên bảng và cột không thay đổi
    show-sql: true
    open-in-view: true

  mvc:
    converters:
      preferred-json-mapper: jackson

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"  # Khóa ký JWT
  valid-duration: 3600  # Thời gian hợp lệ của JWT (giây)
  refreshable-duration: 36000  # Thời gian làm mới JWT (giây)

vnpay:
  tmn-code: FM2YJ74Z  # Mã TMN của VNPay
  hash-secret: M2NXGKZG9WNZ0X8HSRX56TFO6XMWCL75  # Bí mật hash của VNPay
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html  # URL VNPay Sandbox
  return-url: http://localhost:8080/payment/vnpay_return  # URL trả về sau khi thanh toán
