server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: npminhtri.be@gmail.com
    password: cfubhnaxnbdzsnta
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=EducationSystem;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345678
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyNoOpImpl  # Giữ nguyên tên bảng và cột không thay đổi
          implicit-naming-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl  # Giữ nguyên tên bảng và cột không thay đổi
    show-sql: true
    open-in-view: true

  mvc:
    converters:
      preferred-json-mapper: jackson

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in seconds
  refreshable-duration: 36000 # in seconds