server:
  port: ${SERVER_PORT:8080}  # Nếu không có SERVER_PORT trong biến môi trường, mặc định là 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}  # Biến môi trường cho tên người dùng email
    password: ${MAIL_PASSWORD}  # Biến môi trường cho mật khẩu email
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  datasource:
#    url: jdbc:sqlserver://${DB_HOST:abcEnglish.mssql.somee.com}:${DB_PORT:1433};databaseName=${DB_NAME:abcEnglish};encrypt=true;trustServerCertificate=true
#    username: ${DB_USERNAME:MinTrees_SQLLogin_1}  # Biến môi trường cho tên người dùng CSDL
#    password: ${DB_PASSWORD:12345678}  # Biến môi trường cho mật khẩu CSDL
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    hikari:
#      maximum-pool-size: 10

  datasource:
    url: jdbc:sqlserver://${DB_HOST:LAPTOP-TA5GL2KQ}:${DB_PORT:1433};databaseName=${DB_NAME:EducationSystem};encrypt=true;trustServerCertificate=true
    username: ${DB_USERNAME:sa}  # Biến môi trường cho tên người dùng CSDL
    password: ${DB_PASSWORD:12345678}  # Biến môi trường cho mật khẩu CSDL
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}  # Biến môi trường cho kích thước tệp tối đa
      max-request-size: ${MAX_REQUEST_SIZE:10MB}  # Biến môi trường cho kích thước yêu cầu tối đa
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyNoOpImpl
          implicit-naming-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    open-in-view: true

  mvc:
    converters:
      preferred-json-mapper: jackson

jwt:
  signerKey: ${JWT_SIGNER_KEY:"1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"}  # Biến môi trường cho khóa ký JWT
  valid-duration: ${JWT_VALID_DURATION:3600}  # Biến môi trường cho thời gian hợp lệ của JWT
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:36000}  # Biến môi trường cho thời gian làm mới JWT

vnpay:
  tmn-code: ${VNPAY_TMN_CODE:FM2YJ74Z}  # Biến môi trường cho mã TMN của VNPay
  hash-secret: ${VNPAY_HASH_SECRET:M2NXGKZG9WNZ0X8HSRX56TFO6XMWCL75}  # Biến môi trường cho bí mật hash của VNPay
  url: ${VNPAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}  # Biến môi trường cho URL VNPay Sandbox
  return-url: ${VNPAY_RETURN_URL:http://localhost:8080/payment/vnpay_return}  # Biến môi trường cho URL trả về
